networks:
  kestra-network:
    name: kestra-network
    driver: bridge

volumes:
  pgadmin_data:
    driver: local
  postgres-data:
    driver: local
    
services:
  postgres:
    image: postgres
    container_name: postgres-db-kestra
    environment:
      - POSTGRES_USER=kestra
      - POSTGRES_PASSWORD=k3str4
      - POSTGRES_DB=postgres-zoomcamp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kestra-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-kestra
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - kestra-network
